### ISSUE TITLE
Support multiple adversaries

### ISSUE THREAD

**Issue by benbelow** [johnnycopes/spirit-islander#11]
From a few generations and a quick look at the code, it seems that this only supports one adversary at a time. With the rules update in jagged earth, it's possible to play with multiple adversaries.

**Comment by johnnycopes** [comment]
Thanks for the suggestion @benbelow. I've migrated this project to a new repo, but have added https://github.com/johnnycopes/atocha/issues/459 to my backlog to capture this idea.
