### ISSUE TITLE
Make weighted probability possible for scenarios

### ISSUE THREAD

**Issue by ppokellom** [johnnycopes/spirit-islander#14]
I prefer playing without scenarios, but from time to time I have no problem testing one out. As is, the option "No scenario" has the same probability as any scenario selected. I would prefer to be able to say: I want, for example, 60% probability to have no scenario, but if I have one, choose one of the selected at random.

**Comment by johnnycopes** [comment]
Hi @ppokellom, thanks for the suggestion. I've migrated the project to a new repo, but have added this as [a task](https://github.com/johnnycopes/atocha/issues/457) to my backlog.
