### ISSUE TITLE
Avoid boards E+B or F+D in smaller games

### ISSUE THREAD

**Issue by teedyay** [johnnycopes/spirit-islander#18]
Jagged Earth suggests you avoid these map board pairings with fewer than five players. They are particularly swingy in two-player games.

Could we prevent generating games with these pairings?

**Comment by johnnycopes** [comment]
Hi @teedyay, thanks for pointing this out. I've migrated the project and have added this as [a task](https://github.com/johnnycopes/atocha/issues/456) to my backlog.
