### ISSUE TITLE
Thematic board randomizer appears to only suggest board NE

### ISSUE THREAD

**Issue by michaeljjackson** [johnnycopes/spirit-islander#24]

**Comment by kenanoestreich** [comment]
I'm not sure if you're playing solo or not, but if so, the rulebook states to only use northeast for solo games with the thematic map. Hope this helps

**Comment by johnnycopes** [comment]
Hi @michaeljjackson -- what you wrote in the issue title is true, but @kenanoestreich's answer is why it works that way. From page 23 of the base rulebook:

![image](https://github.com/johnnycopes/spirit-islander/assets/14864657/8e9ba218-eeab-4490-b3a1-f0b4523a2784)
