### ISSUE TITLE
Support launching Spirit Island digital

### ISSUE THREAD

**Issue by MigrantP** [johnnycopes/spirit-islander#28]
Hi, I'm John Arnold from Handelabra Games. Just today we released a feature to allow other apps/sites to launch Spirit Island digital via custom URL right into the New Game screen with a given setup in place. If you're interested in integrating that, you can find the details here: https://www.handelabra.com/spirit-island-launch-url-specification

**Comment by johnnycopes** [comment]
Hi John, thanks for the suggestion -- this is a cool idea. I've migrated the project to a separate repo but have added this suggestion as [a task](https://github.com/johnnycopes/atocha/issues/455) to my backlog.
